#!/usr/bin/env python3

import os
import time
import shutil
import subprocess
import sys
import glob

mkdump_path = os.path.expanduser("~/.cache/gstmkdump")
shutil.rmtree(mkdump_path, ignore_errors=True)
os.makedirs(mkdump_path)

print(f"Dumping GStreamer pipelines into {mkdump_path}")
os.environ["GST_DEBUG_DUMP_DOT_DIR"] = mkdump_path

try:
    subprocess.check_call(sys.argv[1:])
except:
    time.sleep(1.0)

xdot_patterns = ["0.00.*-gst-launch.PAUSED_PLAYING.dot", "0.00.*-gst-play.async-done.dot", "*"]
for xdot_pattern in xdot_patterns:
    files = glob.glob(os.path.join(mkdump_path, xdot_pattern))
    if files:
        print("xdot ", files[0])
        #subprocess.check_call(["xdot", files[0]])
        break

